bdc_poll_user:
    resource: "@BDCPollBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user
    
bdc_poll_poll:
    resource: "@BDCPollBundle/Resources/config/routing/poll.yml"
    prefix:   /admin/poll

bdc_poll_question:
    resource: "@BDCPollBundle/Resources/config/routing/question.yml"
    prefix:   /admin/question

bdc_poll_stats:
    resource: "@BDCPollBundle/Resources/config/routing/stats.yml"
    prefix:   /admin/stats


bdc_poll_homepage:
    resource: "@BDCPollBundle/Resources/config/routing/admin.yml"
    prefix:   /

bdc_poll_front:
    resource: "@BDCPollBundle/Resources/config/routing/front.yml"
    prefix: /vote


bdc_poll_email:
    resource: "@BDCPollBundle/Resources/config/routing/email.yml"
    prefix:   /admin/email


