BDC\PollBundle\Entity\Associate:
    type: entity
    table: Associate
    repositoryClass: BDC\PollBundle\Repository\AssociateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 150
    
    oneToMany:
        user:
            targetEntity: User
            mappedBy: associate
    
    lifecycleCallbacks: {  }
