BDC\PollBundle\Entity\Question:
    detect_relations: true
    type: entity
    table: Question
    repositoryClass: BDC\PollBundle\Repository\QuestionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        id_poll:
            type: integer
        
           
        question:
            type: string
            length: 255
      
            
    lifecycleCallbacks: {  }
