BDC\PollBundle\Entity\User:
    detect_relations: true
    type: entity
    table: User
    repositoryClass: BDC\PollBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        last_name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        dni:
            type: string
            length: 255
        associate_id:
            type: integer
        role:
            type: string
            length: 50
        password:
            type: string
            length: 255
        created:
            type: datetime
        modified:
            type: datetime
        salt:
            type: string
    
    manyToOne:
        associate:
            targetEntity: Associate
            inversedBy: user
            joinColumn:
                name: associate_id
                referencedColumnName: id
   
            
    lifecycleCallbacks: {  }
