front_vote:
    path:     /poll
    defaults: { _controller: "BDCPollBundle:Poll:vote" }

front_show:
    path:      /show/{token}/{email}
    defaults: { _controller: "BDCPollBundle:Poll:front_show" }

crom_xml:
    path:     /crontab
    defaults: { _controller: "BDCPollBundle:Email:crontab" }
    
