poll:
    path:     /
    defaults: { _controller: "BDCPollBundle:Poll:index" }

poll_show:
    path:     /{id}/show
    defaults: { _controller: "BDCPollBundle:Poll:show" }

poll_delete:
    path:     /{id}/delete
    defaults: { _controller: "BDCPollBundle:Poll:delete" }

poll_form:
    pattern:  /new
    defaults: { _controller: BDCPollBundle:Poll:form }
    
poll_form_edit:
    pattern:  /edit/{id}
    defaults: { _controller: BDCPollBundle:Poll:form }