user:
    path:     /
    defaults: { _controller: "BDCPollBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "BDCPollBundle:User:show" }

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BDCPollBundle:User:delete" }

user_login:
    path:   /login
    defaults: { _controller: "BDCPollBundle:User:login" }
    
user_logout:
    path:   /logout
    defaults: { _controller: "BDCPollBundle:User:logout" }    

user_form:
    pattern:  /new
    defaults: { _controller: BDCPollBundle:User:form }
    
user_form_edit:
    pattern:  /edit/{id}
    defaults: { _controller: BDCPollBundle:User:form}  
    
user_profile_edit:
    pattern:  /edit/{id}/{profile}
    defaults: { _controller: BDCPollBundle:User:form}      