<?php

namespace BDC\PollBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollRepository extends EntityRepository {

    //se fija si existe otra respuesta igual perteneciente a la encuesta id_poll
    function duplicateAnswer($name, $id, $id_poll = null) {


        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT p
                         FROM BDCPollBundle:Poll p
                         WHERE p.name = :name
                         AND p.id != :id
                         AND p.id_poll = :id_poll'
              
                )->setParameter('name', $name)->setParameter('id', intval($id))->setParameter('id_poll', intval($id_poll));

        $answers = $query->getResult();
        return count($answers) > 0;
    }

    

}
